### ISSUE TITLE
Allow selection of new map during game

### ISSUE THREAD

**Issue by mmonfils** [havok13888/Master-Game#37]
Allow user to press a button which will bring up the map loading screen, allowing the user to select a new map during the game.

**Comment by jamiahuswalton** [comment]
I am trying to allow our game to ask the user to select another map to load when the game restarts. However, the way we currently have it set up, the restart game state is activated when the player pressed Y for the first time. Do we want this?

**Comment by jamiahuswalton** [comment]
Sorry, I started working on this and did not realize you were going to start to work on this. I can push my branch up and you can start working on that branch if you want

**Comment by jamiahuswalton** [comment]
I think we are good with this issue! 

Thanks!
