### ISSUE TITLE
Purpose of Game

### ISSUE THREAD

**Issue by jamiahuswalton** [havok13888/Master-Game#8]
I think that the purpose of the game should be to get through the map as quickly as possible. I'm also thinking that we could make this a multi-player game. You can race your friends and see who can get through the map!

It shouldn't be just how fast you can get through it but how well you can get through it. For example, can you get through and lose the least amount of health as possible? We could also generate a score based on different game components. The player with the highest score wins!

**Comment by JLeezy93** [comment]
What if we added a treasure hunt component? The player walks around the map trying to find the treasure.

**Comment by jamiahuswalton** [comment]
I think that is a good idea. Maybe we can add some time pressure to it as well (e.g., you must find the treasure and get back to the home base in 5 minutes)?

**Comment by wilsont3** [comment]
After talking, we have decided to have the purpose of the game be to look for treasure.  Throughout this, there can be many variations like obstacles in the way (rocks so you have to find a pickaxe, characters, etc.).
